name = "revenue-trackx"
pages_build_output_dir = ".open-next"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]




# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "revenue-trackx-db"
database_id = "a6f44a8c-356e-4576-8c3d-7ca6dc4e31f1"
